project:
  type: website
  output-dir: docs

website:
  title: "sc_bench_benchmark_dashboard"
  sidebar:
    content:
      - href: index.qmd
        text: Papers

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true



