project:
  type: website
  output-dir: docs
  preview:
    port: 4000

website:
  title: "sc_bench_benchmark_dashboard"
  description: "The current landscape and emerging challenges of benchmarking single-cell methods"
  favicon: logo.png
  site-url: https://sydneybiox.github.io/sc_bench_benchmark_dashboard/
  repo-url: https://github.com/SydneyBioX/sc_bench_benchmark_dashboard
  sidebar:
    content:
      - href: index.qmd
        text: Papers
  page-footer:
    left: "&copy; Sydney Precision Data Science Centre 2024"

format:
  html:
    theme: [cosmo]
    toc: true



